/**
 * Database types generated by Supabase CLI
 *
 * Run: pnpm db:types
 * This generates TypeScript types from the Supabase schema
 *
 * This file will be auto-generated when migrations are created in Plan 01
 */

export type Database = Record<string, never>;
